### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by jozajo** [ERR1R/rartracker#6]
Can you please add so that pre-times also shows in browse and a box with 5 or 6 latest forum posts on index?

Best regards

**Comment by ERR1R** [comment]
added pre on browse..  working on  the latest forum posts..

**Comment by jozajo** [comment]
Nice, but it shows pre-time for every torrent now, it should only show where there is a scene release with pre.

**Comment by jozajo** [comment]
Sorry missed a file :)

**Comment by jozajo** [comment]
You should remove showing pre-times in the user profile (snatch log, show torrents and show transfers)

**Comment by ERR1R** [comment]
aha.. i see.. problem is that its using the same table for browse. Need to think about this one..  
i never coded in angular so its all trial and error.

**Comment by jozajo** [comment]
Is there anyplace we can talk more private?
I have lots of ideas :)

**Comment by ERR1R** [comment]
https://discord.gg/bD3YanJ
