### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by jozajo** [ERR1R/rartracker#8]
Reports not working properly.

**Comment by ERR1R** [comment]
do you have more info? sql,  errors etc..

**Comment by ERR1R** [comment]
so i tested the reports, its working fine here..

**Comment by jozajo** [comment]
There are no SQL errors, but it simply not set any value for reason in database.

**Comment by ERR1R** [comment]
maybe its your database Collation?

**Comment by jozajo** [comment]
I use the exact same SQL as in this fork.
All values are added but the "reason" is still empty.

Can it have to be something about subtitles still are remaining in reports?

**Comment by ERR1R** [comment]
mm maybe..

Can you run this one in phpmyadmin:  

https://github.com/ERR1R/rartracker/blob/master/database/fixremovesub.sql

**Comment by ERR1R** [comment]
ps. do you find any errors here:

https://yoururl.com/admin-sqlerrors

**Comment by jozajo** [comment]
There are no errors related to reports in admin-sqlerrors.
Will try the fix within an hour.

**Comment by jozajo** [comment]
The the .sql file did not make the fix :/

**Comment by ERR1R** [comment]
fixed.
